masking:
  fields:
    - email
    - phone
    - password

service.name: fo-order-api
logging:
  level:
    root: info
    org:
      springframework:
        transaction: DEBUG

spring:
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:schema.sql
#      data-locations: classpath:data.sql
  datasource:
    hikari:
      auto-commit: false
    db1:
      username: sa
      password:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp:localhost/~/testdb1;
    db2:
      password:
      username: sa
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp:localhost/~/testdb2;
    db3:
      password:
      username: sa
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp:localhost/~/testdb3;
    db4:
      username: sa
      password:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp:localhost/~/testdb4;
  cloud:
    openfeign:
      client:
        default-config:
            connectTimeout: 5000
            readTimeout: 5000
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
    cache: false
  h2:
    console:
      enabled: true  # H2 콘솔 활성화

management:
  endpoints:
    web:
      base-path: /p
      path-mapping:
        health: status
    health:
      show-details: always
      db:
        enabled: false # 기본 DB 헬스 체크 비활성화
      redis:
        enabled: false # 기본 Redis 헬스 체크 비활성화
server:
  servlet:
    context-path: /api
